CREATE TABLE IF NOT EXISTS "stock_value" (
	"stock" VARCHAR(20) NOT NULL,
	"date" DATE NOT NULL,
	"open" FLOAT NULL DEFAULT NULL,
	"high" FLOAT NULL DEFAULT NULL,
	"low" FLOAT NULL DEFAULT NULL,
	"close" FLOAT NULL DEFAULT NULL,
	"vol" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("stock", "date")
);


CREATE TABLE IF NOT EXISTS "logs" (
	"id" INTEGER PRIMARY KEY,
	"description" VARCHAR(255) NULL,
	"dt" TIMESTAMP NULL DEFAULT NULL,
	"key" VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);